#!/usr/bin/env bash

set -eo pipefail

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
    echo "Usage: $0 <instance id> [basename (under ~/.ssh/include/)]" >&2
    return 1
fi

instance="$1"; shift
if [ $# -gt 0 ]; then
    basename="$1"; shift
else
    basename="$instance"
fi

ssh_include_dir="$HOME/.ssh/include"
mkdir -p "$ssh_include_dir"

while [ 1 ]; do
  hostname="$(ec2_dnsname "$instance")"
  if [ "$hostname" = null ]; then
    echo "Found hostname $hostname, sleeping 1s then re-trying" >&2
    sleep 1
  else
    break
  fi
done
hostname_path="$ssh_include_dir/$basename"
echo "$instance, $hostname_path:" >&2
echo "HostName $hostname" | tee "$hostname_path" >&2
