#!/usr/bin/env bash

set -e

if [ $# -eq 1 ]; then
  aws ec2 describe-instances --instance-ids "$1" | \
  jq '.Reservations[0].Instances[0]|.State,.StateTransitionReason'
elif [ $# -gt 1 ]; then
  for arg in "$@"; do
    echo "$arg:"
    "$0" "$arg"
  done
else
  cat | xargs "$0"
fi
